
module.exports = Object.freeze({
    MODAL_BODY_TYPES : {
        USER_DETAIL : "USER_DETAIL",
        LEAD_ADD_NEW : "LEAD_ADD_NEW",
        PRODUCT_ADD_NEW : "PRODUCT_ADD_NEW",
        PURCHASE_ORDER_ADD_EDIT : "PURCHASE_ORDER_ADD_EDIT",
        ORDER_ADD_EDIT : "ORDER_ADD_EDIT",
        CASH_ADD_EDIT : "CASH_ADD_EDIT",
        CUSTOMER_ADD_EDIT:"CUSTOMER_ADD_EDIT",
        SUPPLIER_ADD_EDIT:"SUPPLIER_ADD_EDIT",
        SUPPLIER_ADD_EDIT : "SUPPLIER_ADD_EDIT",
        CATEGORY_ADD_EDIT : "CATEGORY_ADD_EDIT",
        CONFIRMATION : "CONFIRMATION",
        DEFAULT : "",
    },

    RIGHT_DRAWER_TYPES : {
        NOTIFICATION : "NOTIFICATION",
        CALENDAR_EVENTS : "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES : {
        LEAD_DELETE : "LEAD_DELETE",
        PRODUCT_DELETE : "PRODUCT_DELETE",
        PURCHASE_ORDER_DELETE : "PURCHASE_ORDER_DELETE",
        ORDER_DELETE : "ORDER_DELETE",
        CUSTOMER_DELETE:"CUSTOMER_DELETE",
        CATEGORY_DELETE : "CATEGORY_DELETE",
        SUPPLIER_DELETE : "SUPPLIER_DELETE",
        CASH_DELETE : "CASH_DELETE",
        SUPPLIER_DELETE : "SUPPLIER_DELETE",
    },
});
